import { Safe } from "@/types";
import { OwnershipChart } from "./ownership-chart";
import { KeyMetricsCard } from "./key-metrics-card";

interface ReportProps {
    safes: Safe[];
    futureValuation: number;
    isPostMoney: boolean;
    chartData: { name: string; value: number }[];
    totalSafeInvestment: number;
    totalSharesToSafeHolders: number;
    effectiveSafePrice: number;
}

const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(value);
}

export function Report({ 
    safes, 
    futureValuation, 
    isPostMoney, 
    chartData,
    totalSafeInvestment,
    totalSharesToSafeHolders,
    effectiveSafePrice 
}: ReportProps) {
    return (
        <div className="p-10 bg-white text-black font-body">
            <div className="text-center mb-10">
                <h1 className="text-4xl font-headline font-bold mb-2">SAFE Navigator Scenario Report</h1>
                <p className="text-lg text-gray-600">Generated on: {new Date().toLocaleDateString()}</p>
            </div>

            <div className="space-y-8">
                <div>
                    <h2 className="text-2xl font-headline font-semibold border-b-2 border-gray-300 pb-2 mb-4">Scenario Inputs</h2>
                    <div className="grid grid-cols-2 gap-x-8 gap-y-4 text-lg">
                        <div className="flex justify-between">
                            <span className="font-medium">Hypothetical Valuation:</span>
                            <span className="font-mono">{formatCurrency(futureValuation)}</span>
                        </div>
                        <div className="flex justify-between">
                            <span className="font-medium">SAFE Type:</span>
                            <span className="font-mono">{isPostMoney ? "Post-Money" : "Pre-Money"}</span>
                        </div>
                    </div>
                </div>

                <div>
                    <h2 className="text-2xl font-headline font-semibold border-b-2 border-gray-300 pb-2 mb-4">SAFE Agreements</h2>
                    <div className="space-y-4">
                        {safes.map((safe, index) => (
                             <div key={safe.id} className="p-4 border rounded-lg bg-gray-50">
                                <h3 className="font-semibold text-lg mb-2">SAFE #{index + 1}</h3>
                                <div className="grid grid-cols-2 gap-x-8 text-md">
                                    <div className="flex justify-between">
                                        <span>Investment:</span>
                                        <span className="font-mono">{formatCurrency(safe.investmentAmount)}</span>
                                    </div>
                                    <div className="flex justify-between">
                                        <span>Valuation Cap:</span>
                                        <span className="font-mono">{formatCurrency(safe.valuationCap)}</span>
                                    </div>
                                    <div className="flex justify-between">
                                        <span>Discount:</span>
                                        <span className="font-mono">{safe.discountRate}%</span>
                                    </div>
                                </div>
                             </div>
                        ))}
                    </div>
                </div>

                <div>
                    <h2 className="text-2xl font-headline font-semibold border-b-2 border-gray-300 pb-2 mb-4">Projected Outcomes</h2>
                    <div className="grid grid-cols-2 gap-8 items-start">
                        <div className="mt-[-3rem]">
                            <OwnershipChart data={chartData} />
                        </div>
                        <div>
                             <KeyMetricsCard
                                totalSafeInvestment={totalSafeInvestment}
                                totalSharesToSafeHolders={totalSharesToSafeHolders}
                                effectiveSafePrice={effectiveSafePrice}
                             />
                        </div>
                    </div>
                </div>
            </div>
             <footer className="text-center mt-12 pt-4 border-t text-gray-500 text-sm">
                <p>This report was generated by SAFE Navigator. The calculations are for modeling purposes only and should not be considered financial advice.</p>
            </footer>
        </div>
    );
}
